# Generated by Django 2.2.4 on 2019-10-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retailer',
            new_name='Retailor',
        ),
    ]
